### ISSUE TITLE
New website text changes process

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/dcc-website#13]
How would you like text changes?

For me at least, directly in Master in the github is easiest, that way I also see how it renders. 

In any event, some solution that automates the build process. (I can’t just take the markdown and render it locally, at least not without configuring an environment for it.)

If you want the changes as PRs then I still would like to see how things display (preferably without a local environment). 

Please let us know how you’d like to proceed.

**Comment by kayaelle** [comment]
Hi @bmuramatsu - I discussed with @fields37 and we determined the best way to submit text changes would be to do so via an issue. Whoever works on the issue can share a preview with you or if you'd like to work on this yourself doing PRs, we can help you set up a local environment.

**Comment by kayaelle** [comment]
@bmuramatsu - while we are initially developing the site, you can make updates and preview in this repo: https://github.com/digitalcredentials/dcc-website-jekyll

**Comment by bmuramatsu** [comment]
I would encourage us to not complicate management of the website, it's not that complex and shouldn't take days to update.

It sounds like this is the process you'd like:
- Propose a text change via issue
- Someone else makes the change
- Someone sends the proposer a live preview of the change (it's not particularly useful if it's not a live change on a dev or staging server)
- 0 to many rounds of revision
- Proposer approves the change
- Someone makes a PR
- Someone reviews the PR
- (probably should Publish to staging)
- (probably should review staging)
- Publish to production

That's a lot of work to add a proverbial comma to text.

**Comment by kayaelle** [comment]
@bmuramatsu - Until we migrate the site from the dev one that is being worked on, please submit text updates using the issues provided for each page: 

#4 
#5 
#6 
#7 
#8 

@fields37 will do all coding and text updates until the site is migrated.

After the new site launches, this is the proposed process: 

If it is a simple text change and not a structural change, then the change can be edited directly in github by the submitter. This includes adding text, changing images -- anything that typically can be done in a word processor. This will create a PR that can be reviewed by the dev team who will serve as QA & do the merge. 

Otherwise, if the change requires uploading a file, changing a layout, adding a new page -- anything that can't typically be done by a word processor, an issue and the dev team will act upon it with the submitter on an issue by issue basis. 

Alternatively, you are of course welcome to fork the dcc-website and setup a local environment where you can view your changes and submit PRs which will be be reviewed by the dev team who will serve as QA & do the merge.

**Comment by kayaelle** [comment]
Closing this issue.
