### ISSUE TITLE
Accessibility issue -- use of headings

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/dcc-website#18]
We should only use h1 thru h6 for structural elements. We shouldn't be using it for quotes.

For example on https://digitalcredentials.github.io/dcc-website-jekyll/:
- Shouldn't be h1, We are building an infrastructure for digital academic credentials that can support the education systems of the future.
- Shouldn't be h4, Digital technology has a profound effect on the way we learn.
- Shouldn't be h1, Our mission is to create a trusted, distributed, and shared infrastructure that will become the standard for issuing, storing, displaying, and verifying academic credentials, digitally.
- Shouldn't be h2, Help us build the digital credential infrastructure that fits the future of education.

They should have other named styles, and probably named appropriately. Something like dcc-quote, dcc-highlight or something that describes it's use on the page.

**Comment by fields37** [comment]
Ah, I understand what you were saying now about separating style from structure, that's a pretty serious problem! I've addressed this in https://github.com/digitalcredentials/dcc-website-jekyll/commit/1a7e8470cc7f687cb9be1e61ceaa6308633f982c so that now each page only has one h1, all subheaders are h2, and quotes + action block text are paragraph elements.
