### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/dcc-website#47]
List below for launch. Please include remembering that this pdf was added to the DCC site in the meantime:

https://digitalcredentials.mit.edu/docs/DCC-Making-Sense-of-Key-Data-Standards-for-Verifiable-LERs.pdf

**Comment by fields37** [comment]
I've added the above doc to the DCC-website-jekyll repo so that item should be taken care of!

**Comment by fields37** [comment]
Once we've PR'ed the DCC-website-jekyll repo into the dcc-website repo, the standard Github Pages build action should continue to work with the new Jekyll setup. And the CNAME file should not need to be changed either. Aside from that, there are a couple of files we will need to tweak in order for the whitepaper and 404 redirects to continue working.

- [ ] Change the base href in line https://github.com/digitalcredentials/dcc-website-jekyll/blob/8785d18ef389720c65d4d8641150c5fa37f1b07b/_layouts/default.html#L7 from "https://digitalcredentials.github.io/dcc-website-jekyll/" to "https://digitalcredentials.mit.edu/"
- [ ] Change pathSegmentsToKeep in line https://github.com/digitalcredentials/dcc-website-jekyll/blob/8785d18ef389720c65d4d8641150c5fa37f1b07b/js/redirect.js#L5 from "1" to "0" in order to compensate for the change from a path off of github pages.
